Inc 3
yledovskikh/devops-tpl pull request #3
Opened 2022-04-23 16:00 UTC by yledovskikh

2022-04-25 10:15 UTC, molchalin requested changes

2022-04-25 10:15 UTC, molchalin commented on cmd/server/main.go
> +	r.Post("/update/{metricType}/{metricName}/{metricValue}", handlers.PostMetric)
А почему тут валидация  отличается для GET и POST ?

2022-04-25 10:15 UTC, molchalin commented on internal/handlers/handlers.go
> +		http.Error(w, "404 page not found", http.StatusNotFound)
тут не хватает `return`. И кажется это логичнее в default case в свитч перенести

2022-04-25 10:15 UTC, molchalin commented on internal/handlers/handlers.go
> +	w.WriteHeader(http.StatusOK)
Если что это необязательно, Если не было вызова `WriteHeader`. То автоматически выставится 200

2022-04-25 10:15 UTC, molchalin commented on internal/handlers/handlers.go
> +		panic("error write  client")
Вот так лучше не делать. Сетевая ошибка может привести к панике

2022-04-25 10:15 UTC, molchalin commented on internal/handlers/handlers.go
> +	err := updateMetric(metricType, metricName, metricValue)
А если у нас придет metricType `gAuGe`, то код попадет в `updateMetric`, но там обвалится. Может сразу делать `metricType := strings.ToLower(chi.URLParam(r, "metricType"))` ?

2022-04-25 10:15 UTC, molchalin commented on internal/handlers/handlers_test.go
> +//func TestGetMetric(t *testing.T) {
Надо бы это починить.

2022-04-25 10:15 UTC, molchalin commented on internal/handlers/handlers.go
> +		storage.Gauge[metricName] = vg
мапка не конкуренто безопасная структура, надо как то избежать конкурентных обращений

2022-04-25 10:15 UTC, molchalin commented on internal/agent/collectMetrics.go
> +		sig := <-signalChannel
Можно без `switch` обойтись. у `Signal` есть метод `.String()`. Можно просто делать fmt.Println(sig)

2022-04-25 10:15 UTC, molchalin commented on internal/agent/collectMetrics.go
> +			fmt.Println(err.Error())
тут в случае ошибки продолжится исполнение

2022-04-25 10:15 UTC, molchalin commented on internal/agent/collectMetrics.go
> +		client := &http.Client{}
Создавать клиента на каждый запрос это плохая практика. Тут можно просто `http.DefaultClient` использовать

2022-04-25 10:15 UTC, molchalin commented on internal/agent/collectMetrics.go
> +			os.Exit(1)
Кажется плохо таким образом обрабатывать ошибку. А что если сервер будет лежать? Агент не должен падать из-за этого

2022-04-25 10:15 UTC, molchalin commented on internal/agent/collectMetrics.go
> +			panic(err.Error())
Паника это плохо, надо продумать как тут обрабатывать ошибку

2022-04-25 10:15 UTC, molchalin commented on internal/agent/collectMetrics.go
> +			m = collectMetrics(rtm, 1, r)
pollCounter всегда 1. Это неправильно

2022-04-25 10:15 UTC, molchalin commented on internal/storage/storage.go
> +var Counter = make(map[string]int64)
Реккомендую тут сделать интерфейс, чтобы в будущем можно было заменить на перссистентное хранилище

2022-04-25 10:47 UTC, yledovskikh commented on cmd/server/main.go
> +	r.Post("/update/{metricType}/{metricName}/{metricValue}", handlers.PostMetric)
В тестах есть запросы которые на невалидный PATH ожидают код 501 или 400
Если валидировать путь через regexp, как и для GET, то http сервер возвращает 404 ошибку и тесты не проходят

2022-04-25 15:31 UTC, yledovskikh commented on internal/handlers/handlers.go
> +	err := updateMetric(metricType, metricName, metricValue)
Согласен, лучше сразу сделать преобразование, но можете уточнить, почему updateMetric обвалится?
я вроде в updateMetric перед сравнением привожу к нижнему регистру эту переменную
`switch strings.ToLower(metricType) {
case "gauge":
`

2022-04-25 15:44 UTC, molchalin commented on internal/handlers/handlers.go
> +	err := updateMetric(metricType, metricName, metricValue)
Действительно не обвалится. Видимо куда то в другое место посмотрел

2022-04-25 15:46 UTC, molchalin commented on cmd/server/main.go
> +	r.Post("/update/{metricType}/{metricName}/{metricValue}", handlers.PostMetric)
Я бы придерживался единого стиля валидации. Так код будет понятнее и поддерживаемее. Возможно стоит вынести валидацию параметр и звать её из хэндлеров

2022-05-10 11:23 UTC, molchalin commented on internal/agent/collectMetrics.go
> +	var pollCount int64 = 0
`pollCount` должен обнуляться при каждой отправке

2022-05-10 11:23 UTC, molchalin commented on internal/agent/collectMetrics.go
> +			m = collectMetrics(rtm, pollCount, r)
Кажется, `collectMetrics` правильнее звать прямо перед тем как сделать `postMetrics`

2022-05-10 11:23 UTC, molchalin commented on internal/storage/storage.go
> +type Storage interface {
👍  Хороший интерфейс получился. Код теперь приятно читается

2022-05-10 11:23 UTC, molchalin commented on internal/agent/collectMetrics.go
> +		url := endpoint + "/" + contextURL + "/" + value.metricType + "/" + value.name + "/" + value.value
Тут я бы порекомендовал вынести код, который делает запрос в отдельную функцию и если она вернет ошибку, то уже логировать эту ошибку

2022-05-10 11:23 UTC, molchalin commented on internal/agent/collectMetrics.go
> +		err = response.Body.Close()
Если на строке 60 произойдет ошибка, то `Body` может быть `nil` и мы получим панику. Лучше как я сказал выше вынести это в отдельную функцию и в случае ошибки сразу делать return

2022-05-10 11:24 UTC, molchalin commented
В целом все хорошо. Код стало намного читаемее. Круто, что используешь sync.RWMutex. Осталось немного подправить код агента.

2022-05-10 11:43 UTC, yledovskikh commented on internal/agent/collectMetrics.go
> +			m = collectMetrics(rtm, pollCount, r)
Я возможно не правильно понял задание:

> По умолчанию приложение должно обновлять метрики из пакета runtime с заданной частотой: pollInterval — 2 секунды.
> По умолчанию приложение должно отправлять метрики на сервер с заданной частотой: reportInterval — 10 секунд.

я предполагал такой сценарий - мы локально собираем метрики каждые две сек (пока непонятно зачем) и раз в 10 сек пушим их на сервер. Если это не так, можете уточнить, что именно нужно делать каждые две сек.?

2022-05-10 11:55 UTC, molchalin commented on internal/agent/collectMetrics.go
> +			m = collectMetrics(rtm, pollCount, r)
Вы все верно поняли. Сбор метрик у вас происходит в функции на строчках 80-82. А `collectMetrics` подготавливает их к отправке. Поэтому я предлагаю делать collectMetrics в сам момент отправки.

2022-05-10 12:45 UTC, yledovskikh commented on internal/agent/collectMetrics.go
> +		err = response.Body.Close()
Ок, надеюсь понял идею, сейчас поправлю.

2022-05-11 08:30 UTC, merged